<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="5"
           failures="5"
           errors="0"
           skipped="0"
           time="97.235">
  <properties />
            <testcase name="Invalid_gradecode_test" time="16.151" classname="Scenario_Employ_grade.Scenario_create">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
null, Failed as Expected msg was Grade Code can not be emptyActual msg was   Grade Name already exists!, null, Failed as Expected msg was Grade Code already exists!Actual msg was   Grade Name already exists!"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
null, Failed as Expected msg was Grade Code can not be emptyActual msg was   Grade Name already exists!, null, Failed as Expected msg was Grade Code already exists!Actual msg was   Grade Name already exists!
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
  Scenario_Employ_grade.Scenario_create.Invalid_gradecode_test(Scenario_create.java:122)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
            <testcase name="Invalid_desigcode_test_blnk" time="16.925" classname="Scenario_Employ_grade.Scenario_create">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
null, Failed as Expected msg was Grade Code can not be emptyActual msg was   Grade Name already exists!"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
null, Failed as Expected msg was Grade Code can not be emptyActual msg was   Grade Name already exists!
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
  Scenario_Employ_grade.Scenario_create.Invalid_desigcode_test_blnk(Scenario_create.java:68)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
            <testcase name="Valid_grade_test" time="29.214" classname="Scenario_Employ_grade.Scenario_create">
                <failure type="org.openqa.selenium.NoSuchElementException"
                  message="Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;//*[@id=&apos;GradeTableContainer&apos;]/div/table/tbody/tr[1]/td[2]&quot;}
Command duration or timeout: 10.07 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: &apos;2.44.0&apos;, revision: &apos;76d78cf323ce037c5f92db6c1bba601c2ac43ad8&apos;, time: &apos;2014-10-23 13:11:40&apos;
System info: host: &apos;DJ-PC&apos;, ip: &apos;192.168.30.1&apos;, os.name: &apos;Windows 7&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;6.1&apos;, java.version: &apos;1.8.0_60&apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=31.0, platform=WINDOWS, nativeEvents=true, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: e802baf4-c41d-4fc2-93ff-f5756fa46d10"
              >
<![CDATA[org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//*[@id='GradeTableContainer']/div/table/tbody/tr[1]/td[2]"}
Command duration or timeout: 10.07 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DJ-PC', ip: '192.168.30.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=31.0, platform=WINDOWS, nativeEvents=true, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: e802baf4-c41d-4fc2-93ff-f5756fa46d10
  sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
  sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
  java.lang.reflect.Constructor.newInstance(Unknown Source)
  org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
  org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
  org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
  org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
  org.openqa.selenium.By$ByXPath.findElement(By.java:357)
  org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
  org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:59)
  org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:37)
  com.sun.proxy.$Proxy5.getText(Unknown Source)
  Pageobject_Employ_grade.Pageobject_create.Valid_grade_test(Pageobject_create.java:169)
  Scenario_Employ_grade.Scenario_create.Valid_grade_test(Scenario_create.java:136)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//*[@id='GradeTableContainer']/div/table/tbody/tr[1]/td[2]"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DJ-PC', ip: '192.168.30.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: unknown
  <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///C:/Users/DJ/AppData/Local/Temp/anonymous8238463954561850292webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9641:133)
  <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/DJ/AppData/Local/Temp/anonymous8238463954561850292webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:548:5)
]]>
      </failure>

          </testcase>
            <testcase name="Invalid_designame_test" time="16.466" classname="Scenario_Employ_grade.Scenario_create">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
null, Failed as Expected msg was Grade Code can not be emptyActual msg was   Grade Name already exists!"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
null, Failed as Expected msg was Grade Code can not be emptyActual msg was   Grade Name already exists!
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
  Scenario_Employ_grade.Scenario_create.Invalid_designame_test(Scenario_create.java:95)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
            <testcase name="test_Validcriti" time="18.479" classname="Scenario_Employ_grade.Scenario_create">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
null, Failed as Expected msg was Grade Code can not be emptyActual msg was   Grade Name already exists!, null, Failed as Expected msg was Grade Code already exists!Actual msg was   Grade Name already exists!"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
null, Failed as Expected msg was Grade Code can not be emptyActual msg was   Grade Name already exists!, null, Failed as Expected msg was Grade Code already exists!Actual msg was   Grade Name already exists!
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
  Scenario_Employ_grade.Scenario_create.test_Validcriti(Scenario_create.java:40)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
