<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DJ-PC" name="Scenario_criticality.Scenario_del_criti" tests="1" failures="1" timestamp="18 Nov 2015 11:10:31 GMT" time="0.000" errors="0">
  <testcase name="criti_blnk_test" time="0.000" classname="Scenario_criticality.Scenario_del_criti">
    <failure type="org.testng.TestNGException" message="
Method public void Scenario_criticality.Scenario_del_criti.criti_blnk_test(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : akash in class Dataprovider_currency.DataProvider_del">
      <![CDATA[org.testng.TestNGException: 
Method public void Scenario_criticality.Scenario_del_criti.criti_blnk_test(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : akash in class Dataprovider_currency.DataProvider_del
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- criti_blnk_test -->
</testsuite> <!-- Scenario_criticality.Scenario_del_criti -->
